name: Promote Preview to Production

on:
  workflow_dispatch:
    inputs:
      preview_channel:
        description: 'Preview channel to promote'
        required: true
        type: string

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Production
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          revertOnFailure: true
          channelId: ${{ github.event.inputs.preview_channel }}
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACT_PORTFOLIO_FEF74 }}'
          projectId: your-firebase-project-id
