name: Promote Firebase Preview to Production

on:
  workflow_dispatch: # Allows manual execution

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Promote Firebase Hosting Preview to Production
        run: firebase hosting:channel:deploy live --project=react-portfolio-fef74 --token=${{ secrets.FIREBASE_TOKEN }}

